### ISSUE TITLE
Cache is corrupted when run module with 'nuxt-build-optimisations' module

### ISSUE THREAD

**Issue by sondh0127** [windicss/nuxt-windicss-module#103]
**Describe the bug**
Cache is corrupted when run module with 'nuxt-build-optimisations'. This force build-optimisation re-create the cache.

**To Reproduce**
1. Clone repository '...'
[https://github.com/sondh0127/nuxt-windi-optimize](https://github.com/sondh0127/nuxt-windi-optimize)
2. Run `yarn dev`
3. Close dev server (Ctrl+C)
4. Run `yarn dev`
5. See error

**Expected behavior**
Windi module will work well with module (nuxt-build-optimisations)

**Screenshots**
![image](https://user-images.githubusercontent.com/62163604/123357070-26a21f80-d593-11eb-957a-29480e5b62c1.png)

**Additional context**

**Comment by harlan-zw** [comment]
Hey @sondh0127 

Thanks for the issue and reproduction repo. I followed your instructions and could replicate the bug.

I'm not too familiar with how the hardsource plugin works internally, but I'm guessing it's failing because the pitcher is removed as part of the compilation. Will need to do a proper investigation.

It seems that these "ERROR"s are fine to ignore though. If you want to avoid it you'll need to disable the hardsource plugin either by changing your profile to `experimental` or you can disable hardsource using the feature flag

```js
buildOptimisations: {
  features: {
    hardSourcePlugin: false
  }
}
```

**Comment by sondh0127** [comment]
Thank you @harlan-zw for the quick response. With hardsource disabled, the error is gone. 

But I also hope the module will work with hardsource plugin. It seems fast to me. Hardsource enabled startime reduced 29 seconds to 10 seconds. 

P/S: I will also try 'nuxt-vite' again, but it caused a lot of problems last time.

**Comment by harlan-zw** [comment]
Yup will try find a fix for it

**Comment by harlan-zw** [comment]
Hey @sondh0127. Have found the issue with this and have pushed a release - 1.2.1 which solves it. 

Let me know if you have any further issues :)
