### ISSUE TITLE
Not working with prefix

### ISSUE THREAD

**Issue by izundo-viennv** [windicss/nuxt-windicss-module#24]
I'm using windicss along with Vuetify to avoid conflicting classes , so I need to add prefix in `tailwind.config.js`, but it's not working

**Comment by loonpwn** [comment]
Hey @izundo-viennv. Would you mind sharing your config

**Comment by harlan-zw** [comment]
Have created an issue for this on the main windi repo, will need to wait for a fix there

**Comment by harlan-zw** [comment]
Hi @izundo-viennv. This one should be sorted in the latest update. Please re-open this issue if it's not the case

**Comment by sctouch** [comment]
This still not fixed yet, 

Module Error (from ./node_modules/windicss-webpack-plugin/dist/loaders/virtual-module.js):                                                                                      friendly-errors 11:29:21
(Emitted value instead of an instance of Error) [Windi CSS] Failed to generate CSS. Error: {}
