### ISSUE TITLE
shadow-color not working

### ISSUE THREAD

**Issue by kool-8** [windicss/nuxt-windicss-module#98]
<img width="685" alt="스크린샷 2021-06-14 11 53 49" src="https://user-images.githubusercontent.com/57043683/121833390-330eb880-cd07-11eb-9f93-fa01834d9406.png">

i use `shadow shadow-lime-500 ` in class. but not working

can't find shadow-lime-500 from page when `yarn dev` and `yarn build && yarn start` also.
how can i fix it?

**Comment by harlan-zw** [comment]
Hey @kool-8 

I tried replicating this with the latest version (1.0.3) and wasn't able to. Can you make sure you haven't overridden the colours in the config and that it's not a bug with your CSS?

Otherwise, can you try and replicate it in some way so that I can dig into it.

Also seems to work here: https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIBGB7AHugPgCgopRJZEUMAXAU1xoFoY6A7egJyiQAcFWTAJ5MATIRKky4aPGRp0fAXWFMADADoArBKlTgvSvNoNmcAOZR6jJpkQwA1lBAJODgFzXmAdwAWYeigAM2wOJiQ6AFswHDgQKEjMMV09KQBRTjA2KAAZLJAQzhBJPWAAel5iVLJDOWp0LyZzTgQRLTU1Z1cPRubWpgBmDuDQ5ki6cABXSKheJIGU6oAFTmwQSZgaKDS2cyy6Ok4S-Qqqk5kz0mBMSZoaUKN6zBo2RakAWToUBHM6Y-KbndQmdyhciKDIAQgA&css=HQIw9gHgBA3gUFKABAhgBzQGwJ4MVNbAWgA4CJSoBbFCgdyIGcrqKUBXAFzD0RAHMidABYBLTgFMoAExQAnANYAuAUX5yUxACwAGHTPnLVYNCgDG44gEYdvKHLDsAdtInSiETFEbCU0sAwATJ7evv4MmKJUEkQArHrepmYxxIF2zEqERABs3lRKAGaYEtAZ4hJUjETJTpJyeUqMSSlE%2BhlN5jEU2QDccAC%2BcKCcTrB4qBg4dmgUWgTWUJIQnEwsSyto7HJYMdkJBWC1TBWi4JjSdg7Oru4F7Jhe4HKu9U8vRJvbxUSBCbKKKjAzwkcg%2BWx2pD0dmEYAAbiClOshGJJFAYfC5CpBJ8IXt9OiEW8QUROBonB05BJanYDmZ2IwlI5OJEnDEnIcpLT6Uo5KInIJAlAuQzefywV9dvswHSRXzBGACgVGBIVoE%2BoMgA

**Comment by kool-8** [comment]
@harlan-zw oh.....
i solved it.  problem was version.
my windicss version was 0.4.4....
im sorry 😢
